
remote_theme: broccolini/swiss
title: Swiss Jekyll Theme
description: A bold typographic theme inspired by Swiss design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: jekyll # the GitHub repo name for your project
github_username: jekyll

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: jekyllrb

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black

# Build settings
markdown: kramdown


name: Jeffrey Michael Windsor
personal-tagline: Student of All Things
professional-tagline: Pragmatic · Experienced · Polyglot 
professional-description: I am a highly motivated, passionate and strategically minded technologist with extensive experience in software development, software life cycle management, software languages, tools and technologies.  I have successfully managed, designed and developed a long line of customer facing products and strategic enterprise applications.
professional-highlights:
  - title: Title1
    date: 2018-12-31
    name: name1
    company: company1
    url: https://jeff.windsor.github.io
    description: This is the description of the highlight
    technologies: Haskell, GraphQl, Purescript
  - title: Title2
    date: 2017-12-31
    name: name2
    company: company2
    url: https://jeff.windsor.github.io
    description: This is the description of the highlight2
    technologies: Haskell, GraphQl, Purescript2