theme: minima #hacker minima jekyll-theme-minimal modernist
show_downloads: false
title: Student of All Things
author: Jeff Windsor
description: Husband, Father, Code Junkie, Artist, SciFi Fanatic and Student of All Things
