# Welcome to Jekyll!
#

# Site settings
title: Jeffrey Michael Windsor
description: |
  Pragmatic Experienced Polyglot  
  Student of All Things
owner: Jeffrey Michael Windsor
first_published: 2018
email: jeff.windsor@gmail.com
baseurl: "/"
url: "http://jeffwindsor.github.io"
social:
  twitter: https://twitter.com/jeffwindsor
  github: https://github.com/jeffwindsor?tab=repositories
  linkedin-square: https://www.linkedin.com/in/jeffwindsor
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
